export const omriqGrandPalais = {
  name: "Omriq Grand Palais",
  positioning: "Ultra-luxury demonstration hotel for the Omriq Intelligence Platform.",
  basics: {
    checkIn: "3:00 PM",
    checkOut: "12:00 PM",
    wifi: "Complimentary high-speed Wi‑Fi throughout the property and in all rooms.",
    concierge: "24-hour concierge available by phone, in-app chat, or at the lobby desk.",
    housekeeping: "Housekeeping twice daily with evening turndown service available on request.",
  },
  services: {
    roomService: {
      available: true,
      hours: "24 hours",
      note: "Late-night menu available overnight. Allergy accommodations supported.",
    },
    laundry: {
      available: true,
      note: "Same-day pressing available for early drop-offs.",
    },
    valet: {
      available: true,
      note: "Valet parking available at the main entrance.",
    },
  },
  roomAmenities: {
    connectivity: ["In-room tablet for service requests", "Voice request support", "Multiple USB-C and universal charging ports"],
    comfort: ["Blackout curtains", "Quiet HVAC with 0.5°C precision control", "Premium robe and slippers"],
    refreshments: ["Minibar with non-alcoholic and premium options", "Espresso machine and tea service", "Filtered water on arrival and refill service"],
    bath: ["Deep soaking tub in select rooms", "Rain shower", "Luxury bath amenities", "Hair dryer and styling tools on request"],
    business: ["Dedicated work desk", "International power outlets", "On-request printing via concierge"],
  },
  propertyAmenities: {
    wellness: ["Wellness Spa", "Indoor pool", "Outdoor infinity pool (seasonal)", "Fitness center", "Private training sessions"],
    dining: ["All-day dining", "Breakfast service", "Room service"],
    families: ["Kids Club", "Babysitting", "Family-friendly equipment on request"],
    transport: ["Airport transfers", "Child seats available"],
  },
  climate: {
    lobbyDayC: 21.5,
    lobbyEveningC: 21,
    roomsDefaultC: 21,
    spaC: 23.5,
    gymC: 19.5,
    indoorPoolAirC: 27,
    indoorPoolWaterC: 28,
    roomRangeC: { min: 18, max: 24, increment: 0.5 },
    airQuality: [
      "HEPA-grade air filtration in all rooms",
      "Separate airflow zones for smoking terraces",
      "Hypoallergenic rooms available with medical-grade filtration, no feather products, and natural cleaning agents",
    ],
  },
  sleep: {
    mattresses: [
      { name: "Medium-firm orthopedic", note: "Default" },
      { name: "Firm athletic-support mattress" },
      { name: "Soft plush mattress" },
    ],
    mattressHeightCm: 34,
    threadCount: "600–800 Egyptian cotton",
    duvet: "Seasonal duvet rotation (summer/winter weight)",
    pillowMenu: [
      "Memory foam",
      "Cooling gel",
      "Goose down",
      "Feather-free synthetic",
      "Buckwheat orthopedic",
      "Cervical neck support",
      "Anti-snore incline pillow",
      "Pregnancy support pillow",
    ],
    blackout: "Blackout curtains block 99.8% of external light (tested for urban environments).",
  },
  gym: {
    dumbbellsKg: { min: 2, max: 60, largestSingle: 60 },
    increments: [
      "2–10 kg: 1 kg increments",
      "10–30 kg: 2 kg increments",
      "30–60 kg: 5 kg increments",
    ],
    freeWeights: ["Olympic barbells (20 kg / 45 lb)", "Safety squat bar", "Trap bar", "Adjustable benches (flat, incline, decline)"],
    machines: {
      brands: ["Technogym", "Hammer Strength"],
      list: [
        "Chest press",
        "Shoulder press",
        "Lat pulldown",
        "Seated row",
        "Assisted pull-up / dip machine",
        "Hack squat",
        "Leg press (45°)",
        "Leg curl",
        "Leg extension",
        "Cable crossover (dual adjustable pulley)",
      ],
    },
    cardio: [
      "Treadmills (incline up to 15%)",
      "Stair climbers",
      "Rowing machines (water resistance)",
      "Assault bikes",
      "Ellipticals",
    ],
    extras: ["Stretching & mobility zone", "Foam rollers", "Massage guns", "Private training sessions available", "In-room fitness equipment on request"],
  },
  spa: {
    hours: "8:00 AM to 10:00 PM daily",
    durationsMin: [30, 60, 90],
    treatments: [
      { name: "Swedish Massage", details: "Light to medium pressure. Improves circulation. Ideal for first-time spa guests." },
      { name: "Deep Tissue Massage", details: "Firm pressure. Targets chronic muscle tension. Popular with athletes and business travelers." },
      { name: "Sports Massage", details: "Focus on recovery and mobility. Pre- or post-workout. Custom intensity." },
      { name: "Hot Stone Massage", details: "Basalt stones heated to 50–55°C (122–131°F). Muscle relaxation and stress relief." },
      { name: "Aromatherapy Massage", details: "Essential oils: Lavender (relaxation), Eucalyptus (respiratory relief), Citrus (energy). Allergy consultation required beforehand." },
      { name: "Prenatal Massage", details: "Performed after first trimester only. Side-lying positioning. Unscented oils." },
      { name: "Reflexology", details: "Foot-focused pressure points. Improves circulation and relaxation." },
      { name: "Couples Massage", details: "Private suite. Choice of synchronized treatments." },
    ],
  },
  pools: {
    indoor: { lengthM: 25, lanes: 3, waterC: 28 },
    outdoor: { note: "Outdoor infinity pool with seasonal heating. Cabanas with temperature-controlled cushions. Poolside service." },
    kids: { depthCm: "40–60 cm", waterC: 30, lifeguard: "Lifeguard on duty." },
  },
  dining: {
    allergyProtocolPrompt: "Do you have any allergies or dietary restrictions we should be aware of?",
    allergensTracked: ["Peanuts", "Tree nuts", "Dairy", "Gluten", "Shellfish", "Fish", "Eggs", "Soy", "Sesame", "Sulfites"],
    kitchenCapabilities: ["Separate allergen-prep stations", "Dedicated gluten-free utensils", "Nut-free dessert production area"],
    breakfastExamples: {
      eggs: "Free-range, organic",
      milkOptions: ["Whole", "Skim", "Oat", "Almond", "Soy"],
      bread: ["Sourdough", "Gluten-free", "Rye"],
      fruit: "Sourced daily",
    },
  },
  families: {
    kidsClub: { ages: "3–12", ratio: "1:5 staff-to-child", activities: ["Arts & crafts", "Cooking workshops", "Language games", "Outdoor play"] },
    babysitting: { note: "Certified caregivers available 24 hours with notice. Infant-trained staff available." },
    babyEquipment: ["Baby cots (EU & US safety certified)", "Bottle warmers", "Strollers", "High chairs"],
  },
  transfers: {
    airportMinutes: 35,
    vehicles: ["Luxury sedan", "Electric SUV", "Limousine"],
    childSeats: ["Infant", "Toddler", "Booster"],
  },
} as const;


